---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/pawan3o2/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp privacy-policy.html $DEPLOYPATH
    - /bin/cp terms-of-service.html $DEPLOYPATH
